//Maya ASCII 2025ff03 scene
//Name: rsstandM.ma
//Last modified: Wed, Aug 26, 2026 03:27:29 PM
//Codeset: 936
requires maya "2025ff03";
requires -nodeType "RedshiftNormalMap" -nodeType "RedshiftDisplacement" -nodeType "RedshiftStandardMaterial"
		 "redshift4maya" "2026.3.1";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t pal;
fileInfo "application" "maya";
fileInfo "product" "Maya 2025";
fileInfo "version" "2025";
fileInfo "cutIdentifier" "202409190603-cbdc5a7e54";
fileInfo "osv" "Windows 10 Pro v2009 (Build: 19045)";
fileInfo "UUID" "761183DE-4EF8-AB17-D980-D39A3E05D24E";
createNode file -n "Snow_Road_Albedo";
	rename -uid "7315AC54-4D88-8B4C-4679-F3924358162A";
	setAttr ".ftn" -type "string" "X:/Megascans/Downloaded/surface/snow_mixed_xjikcgnlw/xjikcgnlw_4K_Albedo.jpg";
	setAttr ".ft" 2;
	setAttr ".cs" -type "string" "sRGB";
createNode place2dTexture -n "xjikcgnlw_Coords";
	rename -uid "957B7440-40D3-3C58-028C-F7BE88EFE5D2";
createNode file -n "Snow_Road_Metalness";
	rename -uid "37175ACB-4957-E07A-4D35-5387D62D18FD";
	setAttr ".ail" yes;
	setAttr ".ftn" -type "string" "X:/Megascans/Downloaded/surface/metal_treated_shkxcgfc/shkxcgfc_4K_Metalness.jpg";
	setAttr ".ft" 2;
	setAttr ".cs" -type "string" "Raw";
	setAttr ".ifr" yes;
createNode file -n "Snow_Road_Specular";
	rename -uid "AB355553-43B8-624A-8EB7-458E9CE2E3F5";
	setAttr ".ftn" -type "string" "X:/Megascans/Downloaded/surface/snow_mixed_xjikcgnlw/xjikcgnlw_4K_Specular.jpg";
	setAttr ".ft" 2;
	setAttr ".cs" -type "string" "sRGB";
createNode file -n "Snow_Road_Roughness";
	rename -uid "79FC3DE9-4DBA-C48D-7AD3-25A75835D303";
	setAttr ".ail" yes;
	setAttr ".ftn" -type "string" "X:/Megascans/Downloaded/surface/snow_mixed_xjikcgnlw/xjikcgnlw_4K_Roughness.jpg";
	setAttr ".ft" 2;
	setAttr ".cs" -type "string" "Raw";
createNode RedshiftNormalMap -n "xjikcgnlw_NormalMap";
	rename -uid "F935132D-4D75-91AD-65BE-C4893DC38D3E";
	setAttr ".tex0" -type "string" "X:/Megascans/Downloaded/surface/snow_mixed_xjikcgnlw/xjikcgnlw_4K_Normal.jpg";
createNode RedshiftDisplacement -n "xjikcgnlw_Displacement";
	rename -uid "741B3A19-4778-3929-D52D-B98C8FB9A89B";
	setAttr ".newrange_min" -1;
createNode RedshiftStandardMaterial -n "Snow_Road_Mat";
	rename -uid "2789F04C-44BB-A82F-3D39-35B8149A82F6";
	setAttr ".v" 6;
	setAttr ".ms_mode" 2;
createNode file -n "Snow_Road_Displacement";
	rename -uid "DDC4DD2A-4A16-374D-415E-669656CF08C2";
	setAttr ".ftn" -type "string" "X:/Megascans/Downloaded/surface/snow_mixed_xjikcgnlw/xjikcgnlw_4K_Displacement.exr";
	setAttr ".ft" 2;
	setAttr ".cs" -type "string" "Raw";
createNode shadingEngine -n "Snow_Road_SG";
	rename -uid "F5311097-41B8-3C0A-1884-4F8D7062B7F2";
	setAttr ".ihi" 0;
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo6";
	rename -uid "F5542D05-49E9-8C42-1CE2-76B5A4524314";
createNode lightLinker -s -n "lightLinker1";
	rename -uid "D17BF35E-4A18-C52E-56AD-1BA87C639FE7";
	setAttr -s 10 ".lnk";
	setAttr -s 10 ".slnk";
select -ne :time1;
	setAttr ".o" 1001;
	setAttr ".unw" 1001;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 1;
select -ne :renderPartition;
	setAttr -s 10 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 28 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -s 13 ".u";
select -ne :defaultRenderingList1;
select -ne :defaultTextureList1;
	setAttr -s 40 ".tx";
select -ne :standardSurface1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	setAttr ".ren" -type "string" "redshift";
	setAttr ".outf" 51;
	setAttr ".imfkey" -type "string" "exr";
	setAttr ".fs" 1;
	setAttr ".ef" 10;
	setAttr ".pff" yes;
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr ":defaultColorMgtGlobals.cme" "Snow_Road_Albedo.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "Snow_Road_Albedo.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "Snow_Road_Albedo.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "Snow_Road_Albedo.ws";
connectAttr "xjikcgnlw_Coords.o" "Snow_Road_Albedo.uv";
connectAttr "xjikcgnlw_Coords.ofs" "Snow_Road_Albedo.fs";
connectAttr "xjikcgnlw_Coords.c" "Snow_Road_Albedo.c";
connectAttr "xjikcgnlw_Coords.tf" "Snow_Road_Albedo.tf";
connectAttr "xjikcgnlw_Coords.rf" "Snow_Road_Albedo.rf";
connectAttr "xjikcgnlw_Coords.mu" "Snow_Road_Albedo.mu";
connectAttr "xjikcgnlw_Coords.mv" "Snow_Road_Albedo.mv";
connectAttr "xjikcgnlw_Coords.s" "Snow_Road_Albedo.s";
connectAttr "xjikcgnlw_Coords.wu" "Snow_Road_Albedo.wu";
connectAttr "xjikcgnlw_Coords.wv" "Snow_Road_Albedo.wv";
connectAttr "xjikcgnlw_Coords.re" "Snow_Road_Albedo.re";
connectAttr "xjikcgnlw_Coords.vt1" "Snow_Road_Albedo.vt1";
connectAttr "xjikcgnlw_Coords.vt2" "Snow_Road_Albedo.vt2";
connectAttr "xjikcgnlw_Coords.vt3" "Snow_Road_Albedo.vt3";
connectAttr "xjikcgnlw_Coords.vc1" "Snow_Road_Albedo.vc1";
connectAttr "xjikcgnlw_Coords.n" "Snow_Road_Albedo.n";
connectAttr "xjikcgnlw_Coords.of" "Snow_Road_Albedo.of";
connectAttr "xjikcgnlw_Coords.r" "Snow_Road_Albedo.ro";
connectAttr ":defaultColorMgtGlobals.cme" "Snow_Road_Metalness.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "Snow_Road_Metalness.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "Snow_Road_Metalness.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "Snow_Road_Metalness.ws";
connectAttr "xjikcgnlw_Coords.o" "Snow_Road_Metalness.uv";
connectAttr ":defaultColorMgtGlobals.cme" "Snow_Road_Specular.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "Snow_Road_Specular.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "Snow_Road_Specular.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "Snow_Road_Specular.ws";
connectAttr "xjikcgnlw_Coords.o" "Snow_Road_Specular.uv";
connectAttr "xjikcgnlw_Coords.ofs" "Snow_Road_Specular.fs";
connectAttr "xjikcgnlw_Coords.c" "Snow_Road_Specular.c";
connectAttr "xjikcgnlw_Coords.tf" "Snow_Road_Specular.tf";
connectAttr "xjikcgnlw_Coords.rf" "Snow_Road_Specular.rf";
connectAttr "xjikcgnlw_Coords.mu" "Snow_Road_Specular.mu";
connectAttr "xjikcgnlw_Coords.mv" "Snow_Road_Specular.mv";
connectAttr "xjikcgnlw_Coords.s" "Snow_Road_Specular.s";
connectAttr "xjikcgnlw_Coords.wu" "Snow_Road_Specular.wu";
connectAttr "xjikcgnlw_Coords.wv" "Snow_Road_Specular.wv";
connectAttr "xjikcgnlw_Coords.re" "Snow_Road_Specular.re";
connectAttr "xjikcgnlw_Coords.vt1" "Snow_Road_Specular.vt1";
connectAttr "xjikcgnlw_Coords.vt2" "Snow_Road_Specular.vt2";
connectAttr "xjikcgnlw_Coords.vt3" "Snow_Road_Specular.vt3";
connectAttr "xjikcgnlw_Coords.vc1" "Snow_Road_Specular.vc1";
connectAttr "xjikcgnlw_Coords.n" "Snow_Road_Specular.n";
connectAttr "xjikcgnlw_Coords.of" "Snow_Road_Specular.of";
connectAttr "xjikcgnlw_Coords.r" "Snow_Road_Specular.ro";
connectAttr ":defaultColorMgtGlobals.cme" "Snow_Road_Roughness.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "Snow_Road_Roughness.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "Snow_Road_Roughness.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "Snow_Road_Roughness.ws";
connectAttr "xjikcgnlw_Coords.o" "Snow_Road_Roughness.uv";
connectAttr "xjikcgnlw_Coords.ofs" "Snow_Road_Roughness.fs";
connectAttr "xjikcgnlw_Coords.c" "Snow_Road_Roughness.c";
connectAttr "xjikcgnlw_Coords.tf" "Snow_Road_Roughness.tf";
connectAttr "xjikcgnlw_Coords.rf" "Snow_Road_Roughness.rf";
connectAttr "xjikcgnlw_Coords.mu" "Snow_Road_Roughness.mu";
connectAttr "xjikcgnlw_Coords.mv" "Snow_Road_Roughness.mv";
connectAttr "xjikcgnlw_Coords.s" "Snow_Road_Roughness.s";
connectAttr "xjikcgnlw_Coords.wu" "Snow_Road_Roughness.wu";
connectAttr "xjikcgnlw_Coords.wv" "Snow_Road_Roughness.wv";
connectAttr "xjikcgnlw_Coords.re" "Snow_Road_Roughness.re";
connectAttr "xjikcgnlw_Coords.vt1" "Snow_Road_Roughness.vt1";
connectAttr "xjikcgnlw_Coords.vt2" "Snow_Road_Roughness.vt2";
connectAttr "xjikcgnlw_Coords.vt3" "Snow_Road_Roughness.vt3";
connectAttr "xjikcgnlw_Coords.vc1" "Snow_Road_Roughness.vc1";
connectAttr "xjikcgnlw_Coords.n" "Snow_Road_Roughness.n";
connectAttr "xjikcgnlw_Coords.of" "Snow_Road_Roughness.of";
connectAttr "xjikcgnlw_Coords.r" "Snow_Road_Roughness.ro";
connectAttr "xjikcgnlw_Coords.re" "xjikcgnlw_NormalMap.repeats";
connectAttr "Snow_Road_Displacement.oc" "xjikcgnlw_Displacement.texMap";
connectAttr "xjikcgnlw_NormalMap.oc" "Snow_Road_Mat.bump_input";
connectAttr "Snow_Road_Albedo.oc" "Snow_Road_Mat.base_color";
connectAttr "Snow_Road_Specular.oc" "Snow_Road_Mat.refl_color";
connectAttr "Snow_Road_Roughness.oa" "Snow_Road_Mat.refl_roughness";
connectAttr "Snow_Road_Metalness.oa" "Snow_Road_Mat.metalness";
connectAttr ":defaultColorMgtGlobals.cme" "Snow_Road_Displacement.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "Snow_Road_Displacement.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "Snow_Road_Displacement.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "Snow_Road_Displacement.ws";
connectAttr "xjikcgnlw_Coords.o" "Snow_Road_Displacement.uv";
connectAttr "xjikcgnlw_Coords.ofs" "Snow_Road_Displacement.fs";
connectAttr "xjikcgnlw_Coords.c" "Snow_Road_Displacement.c";
connectAttr "xjikcgnlw_Coords.tf" "Snow_Road_Displacement.tf";
connectAttr "xjikcgnlw_Coords.rf" "Snow_Road_Displacement.rf";
connectAttr "xjikcgnlw_Coords.mu" "Snow_Road_Displacement.mu";
connectAttr "xjikcgnlw_Coords.mv" "Snow_Road_Displacement.mv";
connectAttr "xjikcgnlw_Coords.s" "Snow_Road_Displacement.s";
connectAttr "xjikcgnlw_Coords.wu" "Snow_Road_Displacement.wu";
connectAttr "xjikcgnlw_Coords.wv" "Snow_Road_Displacement.wv";
connectAttr "xjikcgnlw_Coords.re" "Snow_Road_Displacement.re";
connectAttr "xjikcgnlw_Coords.vt1" "Snow_Road_Displacement.vt1";
connectAttr "xjikcgnlw_Coords.vt2" "Snow_Road_Displacement.vt2";
connectAttr "xjikcgnlw_Coords.vt3" "Snow_Road_Displacement.vt3";
connectAttr "xjikcgnlw_Coords.vc1" "Snow_Road_Displacement.vc1";
connectAttr "xjikcgnlw_Coords.n" "Snow_Road_Displacement.n";
connectAttr "xjikcgnlw_Coords.of" "Snow_Road_Displacement.of";
connectAttr "xjikcgnlw_Coords.r" "Snow_Road_Displacement.ro";
connectAttr "Snow_Road_Mat.oc" "Snow_Road_SG.ss";
connectAttr "xjikcgnlw_Displacement.oc" "Snow_Road_SG.ds";
connectAttr "Snow_Road_SG.msg" "materialInfo6.sg";
connectAttr "Snow_Road_Mat.msg" "materialInfo6.m";
connectAttr "Snow_Road_Mat.msg" "materialInfo6.t" -na;
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "Snow_Road_SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "Snow_Road_SG.message" ":defaultLightSet.message";
connectAttr "Snow_Road_SG.pa" ":renderPartition.st" -na;
connectAttr "Snow_Road_Mat.msg" ":defaultShaderList1.s" -na;
connectAttr "xjikcgnlw_NormalMap.msg" ":defaultShaderList1.s" -na;
connectAttr "xjikcgnlw_Displacement.msg" ":defaultShaderList1.s" -na;
connectAttr "xjikcgnlw_Coords.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "Snow_Road_Albedo.msg" ":defaultTextureList1.tx" -na;
connectAttr "Snow_Road_Displacement.msg" ":defaultTextureList1.tx" -na;
connectAttr "Snow_Road_Roughness.msg" ":defaultTextureList1.tx" -na;
connectAttr "Snow_Road_Specular.msg" ":defaultTextureList1.tx" -na;
connectAttr "Snow_Road_Metalness.msg" ":defaultTextureList1.tx" -na;
// End of rsstandM.ma
